/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import method.datareseller.DataReseller;
import method.datareseller.ResellerControl;

/**
 *
 * @author rudi
 */
public class Data_reseller extends javax.swing.JFrame {
int x = 0;
private DefaultTableModel model;
    ResellerControl rc = new ResellerControl();
    DataReseller dr = new DataReseller();
    List<DataReseller> ListReseller = new ArrayList<DataReseller>();
    /**
     * Creates new form Data_reseller
     */
    public Data_reseller() throws SQLException {
        initComponents();
        buatTable();
        showTable();
        bersih();
        siapIsi(false);
        tombolNormal();
        tampilx();
    }

     private void buatTable(){
        model = new DefaultTableModel();
        model.addColumn("Kode Reseller");
        model.addColumn("Nama Reseller");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Status");
        model.addColumn("No HP");
        model.addColumn("Alamat");
        Tabel1.setModel(model);
        
    }
    
    private void showTable(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListReseller.clear();
        ListReseller=rc.tampil();
        for (x=0; x<ListReseller.size(); x++){
            Object[] data=new Object[6];
            data[0]=ListReseller.get(x).getKodereseller();
            data[1]=ListReseller.get(x).getNmreseller();
            data[2]=ListReseller.get(x).getjk();
            data[3]=ListReseller.get(x).getsttus();
            data[4]=ListReseller.get(x).getnohp();
            data[5]=ListReseller.get(x).getalmt();
            model.addRow(data);
        
     }
    }
    
    private void buatKdReseller(){
        ListReseller=rc.tampil();
        int a=ListReseller.size()-1;
        int no=Integer.parseInt(ListReseller.get(a).getKodereseller().replace("R-",""))+1;
        kdrslr.setText("R-"+no);
        kdrslr.setEnabled(false);
    }
    
    private void siapIsi(boolean a){
        kdrslr.setEnabled(a);
        nmrslr.setEnabled(a);
        cmbjk.setEnabled(a);
        sttus.setEnabled(a);
        nohp.setEnabled(a);
        almt.setEnabled(a);
    }

    private void bersih(){
        kdrslr.setText("");
        nmrslr.setText("");
        cmbjk.setSelectedItem("Pilih");
        sttus.setText("");
        almt.setText("");
        nohp.setText("");
    }
    
    private void tombolNormal(){
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        
    }
    
    private void tombolKembali(){
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(true);
    }
    
    public void tampilx()throws SQLException{
        int jmlreseller=rc.getJumlahreseller();
        txtjml.setText(String.valueOf(jmlreseller));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        almt = new javax.swing.JTextField();
        kdrslr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nmrslr = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbjk = new javax.swing.JComboBox<>();
        sttus = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtjml = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(57, 100, 142));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(226, 211, 196));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(245, 160, 75));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 40, 640));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconLogin/icons8-back-64 (1).png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 690));

        jPanel4.setBackground(new java.awt.Color(226, 211, 196));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jPanel6.setBackground(new java.awt.Color(245, 160, 75));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 300, 80));

        jPanel8.setBackground(new java.awt.Color(226, 211, 196));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 170));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 770, 210));

        jPanel9.setBackground(new java.awt.Color(57, 100, 142));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        almt.setBackground(new java.awt.Color(226, 211, 196));
        almt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        almt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        almt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almtActionPerformed(evt);
            }
        });
        jPanel9.add(almt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 290, 50));

        kdrslr.setBackground(new java.awt.Color(226, 211, 196));
        kdrslr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kdrslr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(kdrslr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 290, -1));

        jLabel6.setBackground(new java.awt.Color(48, 99, 118));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setBackground(new java.awt.Color(48, 99, 118));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. HP");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel5.setBackground(new java.awt.Color(48, 99, 118));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel15.setBackground(new java.awt.Color(48, 99, 118));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Status");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel14.setBackground(new java.awt.Color(48, 99, 118));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Jenis Kelamin");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        nmrslr.setBackground(new java.awt.Color(226, 211, 196));
        nmrslr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nmrslr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nmrslr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmrslrActionPerformed(evt);
            }
        });
        jPanel9.add(nmrslr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 290, -1));

        nohp.setBackground(new java.awt.Color(226, 211, 196));
        nohp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nohp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 290, -1));

        jLabel4.setBackground(new java.awt.Color(48, 99, 118));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Reseller");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cmbjk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-laki", "Perempuan" }));
        cmbjk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjkActionPerformed(evt);
            }
        });
        jPanel9.add(cmbjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 290, -1));

        sttus.setBackground(new java.awt.Color(226, 211, 196));
        sttus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sttus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(sttus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 290, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 450, 270));

        jPanel10.setBackground(new java.awt.Color(57, 100, 142));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsimpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconLogin/icons8-save-24 (1).png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel10.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btntambah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconDataBuku/icons8-add-24 (1).png"))); // NOI18N
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel10.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnhapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconLogin/icons8-delete-bin-24 (1).png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel10.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        btnedit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconDataBuku/icons8-edit-24 (1).png"))); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel10.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 450, 50));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cari Berdasarkan");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama Reseller");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 150, -1));

        tcari.setBackground(new java.awt.Color(226, 211, 196));
        tcari.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        jPanel2.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 230, 24));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah Reseller");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        txtjml.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        txtjml.setForeground(new java.awt.Color(245, 160, 75));
        txtjml.setText("100");
        jPanel2.add(txtjml, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 90, 80));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Orang");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, -1));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA RESELLER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconDataMaster/icons8-reseller-64 (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MouseClicked
        int baris = Tabel1.getSelectedRow();

        kdrslr.setText(Tabel1.getModel().getValueAt(baris, 0).toString());
        nmrslr.setText(Tabel1.getModel().getValueAt(baris, 1).toString());
        cmbjk.setSelectedItem(Tabel1.getModel().getValueAt(baris, 2).toString());
        sttus.setText(Tabel1.getModel().getValueAt(baris, 3).toString());
        nohp.setText(Tabel1.getModel().getValueAt(baris, 4).toString());
        almt.setText(Tabel1.getModel().getValueAt(baris, 5).toString());
        siapIsi(false);
        btnhapus.setEnabled(true);
        btnedit.setEnabled(true);
    }//GEN-LAST:event_Tabel1MouseClicked

    private void nmrslrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmrslrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmrslrActionPerformed

    private void cmbjkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjkActionPerformed

    private void almtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almtActionPerformed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        String cari=null;
        cari = tcari.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();;
        ListReseller.clear();
        ListReseller=rc.cariReseller(cari);
        for(x=0; x<ListReseller.size(); x++){
            Object[] data=new Object[6];
            data[0]=ListReseller.get(x).getKodereseller();
            data[1]=ListReseller.get(x).getNmreseller();
            data[2]=ListReseller.get(x).getjk();
            data[3]=ListReseller.get(x).getsttus();
            data[4]=ListReseller.get(x).getnohp();
            data[5]=ListReseller.get(x).getalmt();
            model.addRow(data);

        }
    }//GEN-LAST:event_tcariKeyReleased

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
    if (btntambah.getText().equalsIgnoreCase("Tambah")){
            btntambah.setText("Batal");
            bersih();
            siapIsi(true);
            buatKdReseller();
            nmrslr.requestFocus();
            tombolKembali();
        }else{
            btntambah.setText("Tambah");
            bersih();
            siapIsi(false);
            tombolNormal();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
     if (nmrslr.getText().isEmpty() || cmbjk.getSelectedItem().equals("") ||  sttus.getText().isEmpty() ||  almt.getText().isEmpty() ||
            nohp.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Data Harus Lengkap","Aplikasi Buku", JOptionPane.INFORMATION_MESSAGE);
        }else{
            dr.setKodereseller(kdrslr.getText());
            dr.setNmreseller(nmrslr.getText());
            dr.setjk(cmbjk.getSelectedItem().toString());
            dr.setsttus(sttus.getText());
            dr.setnohp(nohp.getText());
            dr.settalmt(almt.getText());
          
            if(btntambah.getText().equalsIgnoreCase("Batal")){
                if(rc.tambahreseller(dr)==1){
                    JOptionPane.showMessageDialog(null,"Data telah disimpan","Aplikasi Buku", JOptionPane.INFORMATION_MESSAGE);
                    buatTable();
                    showTable();
                    try {
                        tampilx();
                    } catch (SQLException ex) {
                        Logger.getLogger(Data_reseller.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }else{
                    JOptionPane.showMessageDialog(null,"Data gagal disimpan","Aplikasi Buku", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            if(btnedit.getText().equalsIgnoreCase("Batal")){
                if(rc.editReseller(dr)==1){
                    JOptionPane.showMessageDialog(null,"Data telah dirubah","Aplikasi Buku", JOptionPane.INFORMATION_MESSAGE);
                    buatTable();
                    showTable();

                }else{
                    JOptionPane.showMessageDialog(null,"Data gagal dirubah","Aplikasi Buku", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            bersih();
            siapIsi(false);
            btntambah.setText("Tambah");
            btnedit.setText("Edit");
            tombolNormal();

        }
                                            

          // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
       if (btnedit.getText().equalsIgnoreCase("Edit")){
            btnedit.setText("Batal");
            siapIsi(true);
            kdrslr.setEditable(false);
            nmrslr.requestFocus();
            btntambah.setEnabled(false);
            btnsimpan.setEnabled(true);
            btnhapus.setEnabled(false);
            btnedit.setEnabled(true);
            tcari.setText(" ");
            
        }else{
            btnedit.setText("Edit");
            bersih();
            siapIsi(false);
            tombolNormal();
            
        }      // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        dr.setKodereseller(kdrslr.getText());
        int pesan = JOptionPane.showConfirmDialog(null, "Data akan dihapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
         if(pesan==JOptionPane.YES_NO_OPTION){
        if(rc.deleteReseller(dr)==1){
            JOptionPane.showMessageDialog(null,"Data telah dihapus");
            bersih();
            siapIsi(false);
            tombolNormal();
            buatTable();
            showTable();
            try {
                tampilx();
            } catch (SQLException ex) {
                Logger.getLogger(Data_reseller.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Data gagal dihapus");
        }
         }        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_reseller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_reseller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_reseller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_reseller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Data_reseller().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Data_reseller.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel1;
    private javax.swing.JTextField almt;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmbjk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kdrslr;
    private javax.swing.JTextField nmrslr;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField sttus;
    private javax.swing.JTextField tcari;
    private javax.swing.JLabel txtjml;
    // End of variables declaration//GEN-END:variables
}
